name: Build and Release Binaries

on:
  release:
    types: [created] # Trigger only when a new release is created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Build on Linux, Windows, and macOS
        ext: ["", ".exe", ""] # File extensions for each OS
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/release/termidle${{ matrix.ext }}
        asset_name: termidle-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}-${{ github.event.release.tag_name }}${{ matrix.ext }}
        asset_content_type: application/octet-stream
