name: Build and Release Binaries

on:
  release:
    types: [created] # Trigger only when a new release is created

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install jq
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update && sudo apt-get install -y jq
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install jq
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install jq
        fi

    - name: Build binary
      run: cargo build --release

    - name: Determine binary path
      id: binary_path
      run: |
        echo "Determining binary path..."
        BINARY_NAME=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].targets[] | select(.kind[] == "bin") | .name')
        echo "binary_path=target/release/$BINARY_NAME${{ matrix.os == 'windows-latest' && '.exe' || '' }}" >> $GITHUB_ENV

    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.binary_path }}
        asset_name: |
          termidle-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}-${{ github.event.release.tag_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        asset_content_type: application/octet-stream
