name: Release Builds

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: Build Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: termidle
            asset_name: termidle-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: termidle.exe
            asset_name: termidle-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: termidle
            asset_name: termidle-macos-amd64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Asset
        shell: bash
        run: |
          cp "target/${{ matrix.target }}/release/${{ matrix.binary_name }}" "${{ matrix.asset_name }}"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream
